[package]
name = "rsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-primes = "0.2.0"
num-bigint = "0.2.6"
num-integer = "0.1.42"
hex = "0.3.1"
